const { pool } = require('../config/database');
const { PDFDocument, rgb, StandardFonts } = require('pdf-lib');
const cloudinary = require('../config/cloudinary');
const nodemailer = require('nodemailer');

/**
 * F06 — E-Signature / EOI (Expression of Interest) Service
 * Buyer fills form + draws signature → PDF generated → stored on Cloudinary
 * → Agent receives notification email
 */

function getMailer() {
  return nodemailer.createTransport({
    host: process.env.SMTP_HOST, port: parseInt(process.env.SMTP_PORT || '587'),
    secure: false, auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS },
  });
}

function formatPrice(p) {
  if (p >= 10000000) return `₹${(p / 10000000).toFixed(2)} Cr`;
  if (p >= 100000)   return `₹${(p / 100000).toFixed(1)} L`;
  return `₹${Number(p).toLocaleString('en-IN')}`;
}

/**
 * Generate a PDF EOI document and upload to Cloudinary.
 * Returns the secure URL.
 */
async function generateEOIPdf(eoi, listing, agent) {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595, 842]); // A4
  const { width, height } = page.getSize();

  const boldFont   = await doc.embedFont(StandardFonts.HelveticaBold);
  const regularFont = await doc.embedFont(StandardFonts.Helvetica);

  const gold = rgb(0.91, 0.72, 0.29);
  const dark = rgb(0.05, 0.06, 0.08);
  const gray = rgb(0.53, 0.60, 0.67);

  // Background
  page.drawRectangle({ x: 0, y: 0, width, height, color: rgb(0.04, 0.04, 0.06) });
  // Header bar
  page.drawRectangle({ x: 0, y: height - 80, width, height: 80, color: rgb(0.07, 0.09, 0.12) });

  const draw = (text, x, y, { font = regularFont, size = 10, color = rgb(0.93, 0.91, 0.86) } = {}) =>
    page.drawText(text, { x, y, size, font, color });

  // Logo / title
  draw('QR ESTATE', 40, height - 45, { font: boldFont, size: 18, color: gold });
  draw('EXPRESSION OF INTEREST', 40, height - 62, { font: regularFont, size: 9, color: gray });
  draw(`EOI #${eoi.id.slice(0, 8).toUpperCase()}`, width - 160, height - 45, { font: boldFont, size: 10, color: gray });
  draw(new Date(eoi.created_at).toLocaleDateString('en-IN', { day:'numeric', month:'long', year:'numeric' }),
    width - 160, height - 62, { size: 9, color: gray });

  let y = height - 110;
  const section = (title) => {
    page.drawLine({ start: { x: 40, y: y - 5 }, end: { x: width - 40, y: y - 5 }, thickness: 0.5, color: rgb(0.15, 0.2, 0.28) });
    draw(title, 40, y, { font: boldFont, size: 8, color: gold });
    y -= 24;
  };
  const field = (label, value) => {
    draw(label, 40, y, { size: 8, color: gray });
    draw(value || '—', 200, y, { font: boldFont, size: 9, color: rgb(0.93, 0.91, 0.86) });
    y -= 18;
  };

  section('PROPERTY DETAILS');
  field('Property', listing.title);
  field('Location', `${listing.locality ? listing.locality + ', ' : ''}${listing.city}, ${listing.state}`);
  field('Listed Price', formatPrice(listing.price));
  field('Type', `${listing.property_type} · For ${listing.listing_type}`);
  field('Agent', agent.name);
  if (agent.rera_number) field('RERA No.', agent.rera_number);

  y -= 10;
  section('BUYER DETAILS');
  field('Name', eoi.buyer_name);
  field('Phone', eoi.buyer_phone);
  if (eoi.buyer_email) field('Email', eoi.buyer_email);

  y -= 10;
  section('OFFER DETAILS');
  field('Offer Price', formatPrice(eoi.offer_price));
  field('Negotiable?', listing.price_negotiable ? 'Yes' : 'No');
  if (eoi.message) {
    draw('Message', 40, y, { size: 8, color: gray });
    y -= 16;
    const words = eoi.message.split(' ');
    let line = '';
    for (const word of words) {
      if ((line + word).length > 70) {
        draw(line.trim(), 40, y, { size: 9 });
        y -= 15; line = '';
      }
      line += word + ' ';
    }
    if (line.trim()) { draw(line.trim(), 40, y, { size: 9 }); y -= 15; }
  }

  y -= 20;
  section('SIGNATURE');
  draw('Buyer confirms intent to purchase at the stated offer price, subject to due diligence.', 40, y, { size: 8, color: gray });
  y -= 30;

  // Embed signature (base64 PNG) if it's a PNG dataURL
  try {
    if (eoi.signature_data?.startsWith('data:image/png')) {
      const pngBytes = Buffer.from(eoi.signature_data.split(',')[1], 'base64');
      const embeddedImg = await doc.embedPng(pngBytes);
      page.drawImage(embeddedImg, { x: 40, y: y - 60, width: 200, height: 60 });
    }
  } catch { /* skip if malformed */ }

  page.drawLine({ start: { x: 40, y: y - 65 }, end: { x: 260, y: y - 65 }, thickness: 0.5, color: gray });
  draw(eoi.buyer_name, 40, y - 75, { size: 8, color: gray });
  draw('Buyer Signature', 40, y - 87, { size: 7, color: rgb(0.3, 0.35, 0.4) });

  // Footer
  draw('This document is generated by QR Estate. Not a legally binding contract without professional legal review.',
    40, 30, { size: 7, color: rgb(0.25, 0.3, 0.37) });

  const pdfBytes = await doc.save();

  // Upload to Cloudinary
  const uploadResult = await new Promise((resolve, reject) => {
    const stream = cloudinary.uploader.upload_stream(
      { resource_type: 'raw', folder: `qrestate/eoi`, public_id: `EOI_${eoi.id}`, format: 'pdf' },
      (err, res) => { if (err) reject(err); else resolve(res); }
    );
    stream.end(Buffer.from(pdfBytes));
  });

  return uploadResult.secure_url;
}

async function submitEOI({ listingId, buyerName, buyerPhone, buyerEmail, offerPrice, message, signatureData }) {
  // Fetch listing + agent
  const listingRes = await pool.query(
    `SELECT l.*, u.name AS agent_name, u.email AS agent_email, u.rera_number, u.id AS agent_uid
     FROM listings l JOIN users u ON u.id=l.agent_id WHERE l.id=$1 AND l.status='active'`,
    [listingId]
  );
  if (!listingRes.rows.length) throw new Error('Listing not found or not active');
  const listing = listingRes.rows[0];

  // Insert EOI
  const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000); // 7 days
  const eoiRes = await pool.query(
    `INSERT INTO eoi_signatures
       (listing_id, agent_id, buyer_name, buyer_phone, buyer_email, offer_price, message, signature_data, expires_at)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,
    [listingId, listing.agent_uid, buyerName, buyerPhone, buyerEmail, offerPrice, message, signatureData, expiresAt]
  );
  const eoi = eoiRes.rows[0];

  // Generate PDF async (don't block response)
  generateEOIPdf(eoi, listing, { name: listing.agent_name, rera_number: listing.rera_number })
    .then(async (pdfUrl) => {
      await pool.query('UPDATE eoi_signatures SET pdf_url=$1 WHERE id=$2', [pdfUrl, eoi.id]);
      await notifyAgent(listing.agent_email, listing.agent_name, eoi, listing, pdfUrl);
    })
    .catch(console.error);

  return { id: eoi.id, message: 'EOI submitted. The agent will contact you shortly.' };
}

async function notifyAgent(agentEmail, agentName, eoi, listing, pdfUrl) {
  if (!process.env.SMTP_USER) return;
  const mailer = getMailer();
  await mailer.sendMail({
    from: `"QR Estate" <${process.env.SMTP_USER}>`,
    to: agentEmail,
    subject: `New EOI: ${eoi.buyer_name} offered ${formatPrice(eoi.offer_price)} for ${listing.title}`,
    html: `<div style="font-family:sans-serif;max-width:520px;margin:0 auto;background:#07090D;color:#EEE8DC;border:1px solid #1B2330;border-radius:8px;overflow:hidden">
      <div style="background:#0C0F14;padding:20px 24px;border-bottom:1px solid #1B2330">
        <span style="font-weight:800;font-size:16px;color:#E8B84B">QR Estate</span>
        <span style="font-size:11px;color:#566070;margin-left:8px">New Expression of Interest</span>
      </div>
      <div style="padding:24px">
        <h2 style="color:#fff;margin:0 0 4px">New Offer Received 🎉</h2>
        <p style="color:#8899AA;font-size:13px">Hi ${agentName}, ${eoi.buyer_name} has submitted an EOI.</p>
        <div style="background:#0C0F14;border:1px solid #1B2330;border-radius:6px;padding:16px;margin:16px 0">
          <div style="color:#566070;font-size:11px;margin-bottom:4px">OFFER PRICE</div>
          <div style="font-size:24px;font-weight:800;color:#E8B84B">${formatPrice(eoi.offer_price)}</div>
          <div style="color:#8899AA;font-size:12px;margin-top:8px">Property: <b style="color:#fff">${listing.title}</b></div>
          <div style="color:#8899AA;font-size:12px">Buyer: <b style="color:#fff">${eoi.buyer_name} · ${eoi.buyer_phone}</b></div>
          ${eoi.message ? `<div style="margin-top:10px;padding:10px;background:#111C28;border-radius:4px;font-size:12px;color:#8899AA;font-style:italic">"${eoi.message}"</div>` : ''}
        </div>
        ${pdfUrl ? `<a href="${pdfUrl}" style="display:inline-block;background:#E8B84B;color:#000;font-weight:700;padding:10px 20px;border-radius:6px;text-decoration:none;font-size:13px">Download Signed EOI PDF →</a>` : ''}
      </div>
    </div>`,
  });
}

async function getEOIs(listingId, agentId) {
  const res = await pool.query(
    `SELECT es.* FROM eoi_signatures es
     JOIN listings l ON l.id=es.listing_id
     WHERE es.listing_id=$1 AND l.agent_id=$2
     ORDER BY es.created_at DESC`,
    [listingId, agentId]
  );
  return res.rows;
}

async function updateEOIStatus(eoiId, agentId, status) {
  const res = await pool.query(
    `UPDATE eoi_signatures SET status=$1, updated_at=now()
     WHERE id=$2 AND agent_id=$3 RETURNING *`,
    [status, eoiId, agentId]
  );
  if (!res.rows.length) throw new Error('Not found or forbidden');
  return res.rows[0];
}

module.exports = { submitEOI, getEOIs, updateEOIStatus };
